config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :memos, only: [:index, :create, :destroy, :edit]
  resources :notes, only: [:index, :create, :destroy, :edit, :update]

  get'/scrolls/' => 'scrolls#index'
  get'/scroll/example1' => 'scrolls#example1'
  get'/scroll/example2' => 'scrolls#example2'
  get'/scroll/example3' => 'scrolls#example3'
  get'/scroll/example4' => 'scrolls#example4'
  get'/scroll/example5' => 'scrolls#example5'
  get'/scroll/example6' => 'scrolls#example6'

  get'/notes/edit_example' => 'notes#edit_example', as: "edit_example_note"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
	validates :memo, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
	validates :body, presence: true
end

app/models/scroll.rb
class Scroll < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController


	def index
		@memo = Memo.new
		@memos = Memo.all
	end

	def create
		@memo = Memo.new(memo_params)
		if @memo.save
			respond_to do |format|
				format.html{redirect_to root_path}
				format.json
			end
		else
			flash.now[:alert] = "送信に失敗しました。"
			render action: :index
		end
	end

	def destroy
		@memo = Memo.find(params[:id])
		@memo.delete
		redirect_to memos_path
	end

	def edit
	end

	private
	def memo_params
		params.require(:memo).permit(:memo)
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def index
		@note = Note.new
		@notes = Note.all
	end

	def edit_example
		@notes = Note.all
	end

	def edit
	end

	def create
		@note = Note.new(note_params)
		if @note.save
			respond_to do |format|
				format.html { redirect_to notes_path }
				format.json { render json: {body: @note.body,
											id: @note.id
											}
							}
			end
		end
	end

	def update
		@note = Note.find(params[:id])
		if @note.update!(note_params)
			respond_to do |format|
					format.html{ redirect_to edit_example_path }
					format.json{ render json: {body: @note.body,
												id: @note.id
												}
									}
			end
		end
	end

	def destroy
		@note = Note.find(params[:id])
		if @note.destroy
			respond_to do |format|
				format.html { redirect_to notes_path }
				format.json { render json: { id: params[:id]} }
			end
		end
	end

	private
	def note_params
		params.require(:note).permit(:body)
	end
end

app/controllers/scrolls_controller.rb
class ScrollsController < ApplicationController

	def index
	end

	def example1
	end

	def example2
	end

	def example3
	end

	def example4
	end

	def example5
	end

	def example6
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/scrolls_helper.rb
module ScrollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TryRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/scrollreveal"></script>
    <script src="https://kit.fontawesome.com/fff3ba2388.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/index.html.erb
<div class="container">
	<div class="row">
		<div class="memos">
			<ul>
				<% @memos.each do |t| %>
					<li><%= t.memo %></li>
					<li><%= link_to "削除", memo_path(t), method: :delete, class: "btn btn-danger" %></li>
					<br>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="new_memo">
			<%= form_with model: @memo, id: "new_form" do |f| %>
				<%= f.label :memo, "入力フォーム" %>
				<%= f.text_area :memo, size: "100x1", placeholder: "記入してください" %>
				<%= f.submit "メモを作成" %>
			<% end %>
		</div>
	</div>

	<script>
		$(document).on('turbolinks:load', function(){
			function buildHTMl(body){
				var content = body.memo ? `${body.memo}` : "";
				var html = `<ul>
								<li>
									${content}
								</li>
							</ul>`
				return html;
			};
			$('#new_form').on('submit', function(event){
				event.preventDefault();
				console.log("start")
				// var memo = new FormData(this);
				const inputText = document.getElementById("memo_memo").value;
				// const memo = $("#new_form [memo=memo]").val();
				console.log(inputText);
				var url = $(this).attr('action');
				$.ajax({
					url: url,
					type: 'POST',
					data: {memo: {memo: inputText}},
					dataType: 'json',
					processData: false,
					contentType: false
				})
				.done(function(data){
					var html = buildHTML(data);
					$(".memos").append(html);
					$("#memo_memo").val("");
				})
				.fail(function(data){
					alert('エラーが発生したためメッセージが送信できませんでした');
				})
			});
		});
	</script>
</div>

app/views/notes/edit_example.html.erb
<h1>コメントの編集機能の実装</h1>

<div>
	<% @notes.each do |note| %>
		<!-- 編集ボタン -->
		<span data-note-id=<%= note.id %> class="js-edit-note-button">
			<i class="fas fa-edit text-primary"></i>
		</span>
		<!-- 一意のコメント -->
		<div id="js-note-<%= note.id %>">
			<p id="js-note-label-<%= note.id %>"><%= note.body %></p>
			<p id="js-note-post-error-<%= note.id %>" class="text-danger"></p>
			<textarea style="display: none" id="js-textarea-note-<%= note.id %>" class="form-control note-post-error"><%= note.body %></textarea>
			<div id="js-note-button-<%= note.id %>" style="display: none;">
				<button data-cancel-id=<%= note.id %> type="button" class="btn btn-light note-cancel-button">キャンセル</button>
				<button data-update-id=<%= note.id %> type="submit" class="btn btn-success note-update-button">更新</button>
			</div>
		</div>
	<% end %>
</div>

app/views/notes/index.html.erb
<h1>noteの非同期通信で作成、削除</h1>
<div class="form">
	<%= form_with(model: @note, class: "note_form", id: "note_input", local: true) do |form| %>
		<%= form.text_area :body, class: "note_form-text" %>
		<%= form.submit "メモを登録", class: "note_form-btn" %>
	<% end %>
</div>

<div class="notes">
	<% @notes.each do |note| %>
		<div class="note" id="note<%= note.id %>">
			<div class="note_name">
				投稿者: ユーザー機能未実装
			</div>
			<p id="js-note-label-<%= note.id %>" class="note_body"><%= note.body %></p>
			<div class="">
				<!-- ↓edit/update -->
				<span data-note-id=<%= note.id %> class="js-edit-note-button">
					<i class="fas fa-edit text-primary">編集</i>
				</span>
				<p id="js-note-post-error-<%= note.id %>" class="text-danger"></p>
				<textarea style="display: none" id="js-textarea-note-<%= note.id %>" class="form-control note-post-error"><%= note.body %></textarea>
				<div id="js-note-button-<%= note.id %>" style="display: none;">
					<button data-cancel-id=<%= note.id %> type="button" class="btn btn-light note-cancel-button">キャンセル</button>
					<button data-update-id=<%= note.id %> type="submit" class="btn btn-success note-update-button">更新</button>
				</div>
				<!-- ↑edit/update -->
				<%= link_to note_path(note.id), class: "note_delete", method: :delete do %>
					<i class="fas fa-trash-alt" style="color: black;">削除</i>
				<% end %>
			</div>
			<br>
		</div>
	<% end %>
</div>

app/views/scrolls/example1.html.erb
<h1 class="mainTitle">
	Intersection Observer API Demo
</h1>
<div class="wrapper">
	<aside class="indexWrapper">
		<h1>目次</h1>
			<ol id="indexList" class="index">
			  <li><a href="#index1">Lorem</a></li>
			  <li><a href="#index2">Ipsum </a></li>
			  <li><a href="#index3">Dolor</a></li>
			  <li><a href="#index4">Sit amet</a></li>
			  <li><a href="#index5">Consectetur</a></li>
			</ol>
	</aside>
	<main class="contents">
		<div class="box" id="index1">
		  <h1>Lorem</h1>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>

		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    <img src="./photo.jpg" alt="" width="720" height="480" />
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		</div>

		<div class="box" id="index2">
		  <h1>Ipsum</h1>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    <img src="./photo.jpg" alt="" width="720" height="480" />
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>

		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		</div>

		<div class="box" id="index3">
		  <h1>Dolor</h1>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		</div>

		<div class="box" id="index4">
		  <h1>Sit amet</h1>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    <img src="./photo.jpg" alt="" width="720" height="480" />
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		</div>

		<div class="box" id="index5">
		  <h1>Consectetur</h1>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    <img src="./photo.jpg" alt="" width="720" height="480" />
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    <img src="./photo.jpg" alt="" width="720" height="480" />
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		  <p>
		    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
		    Accusantium asperiores expedita minus nisi praesentium provident
		    quisquam repellat sapiente ut vitae. Aut corporis deleniti deserunt
		    eos error facere, maiores necessitatibus quo.
		  </p>
		</div>
	</main>
</div>

app/views/scrolls/example2.html.erb
<!-- スクロールで画像を入れ替える
やり方は画像の表示をactiveで切り替え -->


<div class="image-wrapper">
	<div id="imageList" class="lists">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
		<div class="image5"></div>
	</div>

	<div class="contents">
		<div class="top-box" id="image1"></div>
		<div class="top-box" id="image2"></div>
		<div class="top-box" id="image3"></div>
		<div class="top-box" id="image4"></div>
		<div class="top-box" id="image5"></div>
	</div>
</div>

<script src="https://unpkg.com/scrollreveal"></script>

app/views/scrolls/example3.html.erb
<h1>ScrollReveal.jsの導入</h1>

<div class="container">
  <div class="row">
    <div class="box-1">
    	<div class="text1">right</div>
    </div>
    <div class="box-1">
    	<h2 class="text2">bottom</h2>
    </div>
    <div class="box-1"></div>
  </div>
  <div class="image6"></div>
  <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
  <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
  <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
   <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
   <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
   <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
  <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
  <div class="row">
    <div class="box-1"></div>
    <div class="box-1"></div>
    <div class="box-1"></div>
  </div>
</div>

app/views/scrolls/example4.html.erb
<!-- 画像の切り替えをz-indexの重なりで切り替えてみる -->

<div class="image-wrapper">
	<div id="imageList2" class="lists2">
		<div class="image6"></div>
		<div class="image7"></div>
		<div class="image8"></div>
		<div class="image9"></div>
		<div class="image10"></div>
	</div>

	<div class="contents">
		<div class="top-box2" id="image6"></div>
		<div class="top-box2" id="image7"></div>
		<div class="top-box2" id="image8"></div>
		<div class="top-box2" id="image9"></div>
		<div class="top-box2" id="image10"></div>
	</div>
</div>

<script src="https://unpkg.com/scrollreveal"></script>

app/views/scrolls/example5.html.erb
<div id="imageList3" class="lists3">
	<div class="image-style image11">
		<div class="image-cover"></div>
		<div class="text-box image11">
			<p class="text-item">
				こんにちは<br>
				おはよう<br>
				こんばんは
			</p>
		</div>
	</div>
	<div class="image-style image12">
		<div class="image-cover"></div>
		<div class="text-box image12">
			<p class="text-item">
				こんにちは<br>
				おはよう<br>
				こんばんは
			</p>
		</div>
	</div>
	<div class="image-style image13">
		<div class="image-cover"></div>
		<div class="text-box image13">
			<p class="text-item">
				こんにちは<br>
				おはよう<br>
				こんばんは
			</p>
		</div>
	</div>
	<div class="image-style image14">
		<div class="image-cover"></div>
		<div class="text-box image14">
			<p class="text-item">
				こんにちは<br>
				おはよう<br>
				こんばんは
			</p>
		</div>
	</div>
	<div class="image-style image15">
		<div class="image-cover"></div>
		<div class="text-box image15">
			<p class="text-item">
				こんにちは<br>
				おはよう<br>
				こんばんは
			</p>
		</div>
	</div>
</div>

<div class="contents">
	<div class="top-box3" id="image11"></div>
	<div class="top-box3" id="image12"></div>
	<div class="top-box3" id="image13"></div>
	<div class="top-box3" id="image14"></div>
	<div class="top-box3" id="image15"></div>
</div>


<script src="https://unpkg.com/scrollreveal"></script>

app/views/scrolls/example6.html.erb
<!-- 慣性スクロールの停止 -->

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content stop">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content stop">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content stop">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content stop">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

<div class="content">
    <p>ほげほげ</p>
</div>

app/views/scrolls/example7.html.erb
<h2>矢印を作って下線をひく</h2>

app/views/scrolls/index.html.erb
<h1>index</h1>
<ol>
	<li><%= link_to "example1", '/scroll/example1' %></li>
	<li><%= link_to "example2", '/scroll/example2' %></li>
	<li><%= link_to "example3", '/scroll/example3' %></li>
	<li><%= link_to "example4", '/scroll/example4' %></li>
	<li><%= link_to "example5", '/scroll/example5' %></li>
	<li><%= link_to "example6", '/scroll/example6' %></li>
</ol>